dfinity/eslint-config-oisy-wallet

package.json

Repo fields are missing in `package.json` and therefore we cannot publish to npm.
See https://github.com/dfinity/eslint-config-oisy-wallet/actions/runs/11053281386/job/30707280793

build: missing repo fields for publish

---

README.md
package-lock.json
package.json

Using this library currently does not work. The root cause is the usage of the `eslint-plugin-local-rules` plugin which require a configuration file at the root of the project where the plugin is used. Not much we can do. Therefore, I tweaked this library to expose the rules we have developed and added an explanation in the README.
I also bumped the lib version as I'll release a new version afterwards.

fix: eslint-local-rules usage

---

eslint-local-rules.cjs
package-lock.json
package.json
rule-tester-setup.ts
tests/use-option-type-wrapper.spec.ts
tsconfig.json
vitest.config.ts

We create the test framework for [RuleTester](https://typescript-eslint.io/packages/rule-tester), that is an util to test lint rules.
- Change TS config to use `"moduleResolution": "bundler"`.
- Install `vitest` and `@typescript-eslint/rule-tester`.
- Define RuleTester setups giving the same functions as `vitest`, as suggested by [documentation](https://typescript-eslint.io/packages/rule-tester#vitest).
- Define `vitest` configurations.
To check if it works, we create a first test on existing rule `use-option-type-wrapper`. Note that RuleTester requires message IDs instead of hard-coded messages, when a rule is triggered.

feat: add test framework and create test for one rule

---

index.cjs

With the aim of helping us making everything more function, we add rule [prefer-const](https://eslint.org/docs/latest/rules/prefer-const).
The rule prevents unnecessary mutable variable when the variable is not reassigned. Note that we use it only in Typescript files because the `svelte` files require prop and variable declarations to be mutable.

feat: include rule to enforce usage of const

---

eslint-local-rules.cjs

In the signer standards lib I got following warning:
> /Users/daviddalbusco/projects/dfinity/oisy-wallet-signer/src/icp-wallet.ts
>  104:53  warning  Functions with more than one parameter should accept an object and use destructuring  local-rules/prefer-object-params
I think it's because I use `every` which is not yet whitelisted
```
const uint8ArrayEqual = ({first, second}: {first: Uint8Array; second: Uint8Array}): boolean =>
first.length === second.length && first.every((value, index) => value === second[index]);
```
Therefore I thought about adding more functions to the list of exception of `prefer-object-params`.

feat: more array functions exceptions for prefer-object-params

---

eslint-local-rules.cjs
index.cjs
tests/no-relative-imports.spec.ts

We introduce the rule [no-relative-parent-imports](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-relative-parent-imports.md) that enforces the usage of absolute imports or aliases, but only if it refers to parent peers.
To completely avoid relative imports, we create a custom rule that simply check the import string.

feat: avoid relative imports

---

index.cjs

We introduce [require-await](https://eslint.org/docs/latest/rules/require-await) rule, that enforce to await async functions.
It is a bit an opinionated: some projects accepts a lot of of async functions that are not awaited, so it become full of exceptions.
But we do it only in a few strategic places.

feat: Add require-await rule

---

eslint-local-rules.cjs
rules/explicit-non-void-return-type.js
tests/explicit-non-void-return-type.spec.ts

We want to introduce a new custom rule that enforces the declaration of non-void return types
```typescript
function foo() { 
return 42; 
}
const foo = function() { 
return "hello"; 
}
const foo = () => { 
return true; 
}
const bar = async function() { 
return 42; 
}
async function bar() { 
return true; 
}
```
```typescript
function foo(): number { 
return 42; 
}
const foo = function(): string { 
return "hello"; 
}
const foo = (): boolean => true;
const bar = async function(): Promise<number> { 
return Promise.resolve(42); 
}
async function bar(): Promise<boolean> { 
return Promise.resolve(true); 
}
function foo() { 
// No return value
}
const foo = function() { 
// No return value
}
const foo = () => { 
// No return value
}
const bar = async function() { 
// No return value
}
async …
```

feat: add new rule explicit-non-void-return-type

---

index.cjs
package-lock.json
package.json
rules/explicit-non-void-return-type.cjs
rules/no-relative-imports.cjs
rules/no-svelte-store-in-api.cjs
rules/prefer-object-params.cjs
rules/use-nullish-checks.cjs
rules/use-option-type-wrapper.cjs

This is a duplicate of PR #30 , because I changed my account.
To further help with enforcing the arrow functions we add two rules and one plugin. This is one of the most suggested combination I found online:
- [prefer-arrow-callback](https://eslint.org/docs/latest/rules/prefer-arrow-callback): this will enforce arrow functions when given as callback to other statements;
- [func-style](https://eslint.org/docs/latest/rules/func-style): the default settings of this rule forces to avoid using declaration statements for functions, for example `function foo() {...}`
- [prefer-arrow](https://www.npmjs.com/package/eslint-plugin-prefer-arrow) plugin: with the configs set by us, the plugin will generally make notice of the usage of `function`.
- Installed plugin …

feat: Add rules to enforce arrow functions

---

index.cjs

We include rule [consistent-type-imports](https://typescript-eslint.io/rules/consistent-type-imports/), that, among other things, will change:
```typescript
import { type CustomType } from 'types.ts'
import { type CustomType1, type CustomType2 } from 'types.ts'
```
to 
```typescript
import type { CustomType } from 'types.ts'
import type { CustomType1, CustomType2 } from 'types.ts'
```

feat: add rule consistent-type-imports

---

index.cjs

We cannot migrate to eslint v9 and introduce new rules at the same time.
- Disable all rules introduced since last release.

feat: disable new eslint rules

---

package-lock.json
package.json

We don't want to force consumer to use explicitely `@dfinity/utils` or `typescript` version x.y.z. The version should not be given by eslint but by the need of features.

feat: do not enforce precise version of utils and typescript

---

package-lock.json
package.json

We want to bump the requirement for eslint svelte as we migrate to Svelte v5.

build: bump eslint-plugin-svelte

---

svelte.mjs

We would like to include Svelte lint rules [shorthand-attribute](https://sveltejs.github.io/eslint-plugin-svelte/rules/shorthand-attribute/) and [shorthand-directive](https://sveltejs.github.io/eslint-plugin-svelte/rules/shorthand-directive/) to keep the code a bit cleaner: they enforce the usage of shorthand syntax, for example:
```svelte
<button {disabled}>...</button>
<button disabled={disabled}>...</button>
```

feat: add Svelte rules shorthand-attribute and shorthand-directive

---

svelte.mjs

Just to keep it "prettier", we add Svelte rule [spaced-html-comment](https://sveltejs.github.io/eslint-plugin-svelte/rules/spaced-html-comment/).

feat: add Svelte check rule spaced-html-comment

---

svelte.mjs

Maybe opinionated, but I would like to add Svelte check rule [no-extra-reactive-curlies](https://sveltejs.github.io/eslint-plugin-svelte/rules/no-extra-reactive-curlies/) that disallows wrapping single reactive statements in curly braces.

feat: add Svelte check rule no-extra-reactive-curlies

---

svelte.mjs

Maybe opinionated, but I think the language of the blocks of a Svelte component should be explicit. So, with this PR, we introduce the Svelte rule [block-lang](https://sveltejs.github.io/eslint-plugin-svelte/rules/block-lang/) that disallows the use of languages other than those specified in the configuration for the lang attribute of <script> and <style> blocks.
We set it to be always present in both blocks as:
- `script`: Typescript
- `style`: Sass and Postcss

feat: add Svelte check rule block-lang

---

configs/eslint.rules.mjs

I would like to introduce the eslint rule [object-shorthand](https://eslint.org/docs/latest/rules/object-shorthand) that requires method and property shorthand syntax for object literals.

feat: add rule object-shorthand

---

svelte.mjs

Rule `svelte/block-lang` is too restrictive: we can allow to have missing blocks.

feat: rule svelte/block-lang should allow for missing blocks

---

svelte.mjs

Preferably there are no unnecessary newlines between imports. So we set option [newlines-between](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md#newlines-between) of rule `import/order` to `never`.

feat: add option newlines-between to rule import/order

---

package-lock.json
package.json
vitest.mjs

Create an additional set of rules, specific for vitest, using [eslint-plugin-vitest](https://github.com/vitest-dev/eslint-plugin-vitest).
For now the default rules are not many, but we will add more from the [list](https://github.com/vitest-dev/eslint-plugin-vitest?tab=readme-ov-file#rules).
- Install [eslint-plugin-vitest](https://github.com/vitest-dev/eslint-plugin-vitest).
- Create index file `vitest.mjs` with the recommended rules from the new plugin.
- Include `vitest` rules in the package.
Not applicable.

feat: add vitest rules with eslint-plugin-vitest

---

vitest.mjs

According to [documentation](https://github.com/vitest-dev/eslint-plugin-vitest?tab=readme-ov-file#usage), and in preparation to add more rules to the `vitest` linter, we refactor how we import the vitest plugin rules, using the syntax plugins-rules, that apparently is the only structure that works if we want to add/remove more rules as single options.
For example:
```typescript
{
plugins: {      vitest    },
rules: {
...vitest.configs.recommended.rules, 
"vitest/valid-expect-in-promise": ["error"]
},
},
```

refactor: use plugins-rules syntax for vitest linter

---

vitest.mjs

To have a more organized test structure, we include vitest rule [no-duplicate-hooks](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/no-duplicate-hooks.md) that enforces avoiding duplicated hooks.

feat: add vitest rule no-duplicate-hooks

---

configs/eslint.rules.mjs

The rule [@typescript-eslint/consistent-type-imports](https://typescript-eslint.io/rules/consistent-type-imports/) has by default option `fixStyle: "separate-type-imports"` so we can remove it.
Furthermore there was a leftover TODO related to this rule, we can remove it too.

refactor: remove TODO and default option for rule consistent-type-imports

---

vitest.mjs

To have a more organized test structure, we include vitest rule [padding-around-all](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/padding-around-all.md) that enforces padding around hooks and test statements.

feat: add vitest rule padding-around-all

---

vitest.mjs

To have a more organized test structure, we include vitest rule [prefer-hooks-in-order](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/prefer-hooks-in-order.md) that enforces a specific order of the hooks: 
```typescript
// consistent order of hooks
['beforeAll', 'beforeEach', 'afterEach', 'afterAll']
```

feat: add vitest rule prefer-hooks-in-order

---

vitest.mjs

To have a more organized test structure, we include vitest rule [prefer-hooks-on-top](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/prefer-hooks-on-top.md) that enforces hooks to be before the tests..

feat: add vitest rule prefer-hooks-on-top

---

vitest.mjs

To have more consistency in the tests, we include vitest rules [prefer-to-be-object](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/prefer-to-be-object.md):
```ts
// bad
expectTypeOf({}).not.toBeInstanceOf(Object);
// good
expectTypeOf({}).not.toBeObject();
```

feat: add vitest rule prefer-to-be-object

---

configs/eslint.rules.mjs
rules/explicit-non-void-return-type.cjs
rules/prefer-object-params.cjs

We had rule [prefer-destructuring](https://eslint.org/docs/latest/rules/prefer-destructuring) that:
> Require destructuring from arrays and/or objects

feat: add rule `prefer-destructuring`

---

vitest.mjs

To have more consistency in the tests, we include vitest rules [prefer-each](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/prefer-each.md) that enforce the use of `.each` loop instead of `for` loops.

feat: add vitest rule `prefer-each`

---

configs/eslint.rules.mjs

We had rule  [@typescript-eslint/no-import-type-side-effects](https://typescript-eslint.io/rules/no-import-type-side-effects/) that:
> Enforce the use of top-level import type qualifier when an import only has specifiers with inline type qualifiers.

feat: add rule `no-import-type-side-effects`

---

configs/eslint.rules.mjs

We can re-instate rules `func-style`, `prefer-arrow-callback`, and `prefer-arrow-functions`: I tested them all in OISY and it was smoothly handled.

feat: re-instate rules `func-style`, `prefer-arrow-callback` and `prefer-arrow-functions`

---

vitest.mjs

To have more consistency in the tests, we include vitest rules [require-top-level-describe](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/require-top-level-describe.md) that warns if a test case or a hook is not located in a top-level `describe` block.

feat: add vitest rule `require-top-level-describe`

---

vitest.mjs

To have more consistency in the tests, we include vitest rules [prefer-equality-matcher](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/prefer-equality-matcher.md) that aims to enforce the use of the built-in equality matchers.
```ts
// bad 
expect(1 == 1).toBe(1)
// bad
expect(1).toEqual(1)
```

feat: add vitest rule `prefer-equality-matcher`

---

rules/prefer-object-params.cjs

Loop function `some` is missing among the exceptions of rule `prefer-object-params`.

fix: add `some` among the exceptions of rule `prefer-object-params`

---

configs/eslint.rules.mjs

We add TS lint rule [no-unnecessary-condition](https://typescript-eslint.io/rules/no-unnecessary-condition/) that warns about unnecessary coalescing in objects.

feat: add TS rule `no-unnecessary-condition`

---

configs/eslint.rules.mjs

Adding TS lint rule [no-non-null-asserted-nullish-coalescing](https://typescript-eslint.io/rules/no-non-null-asserted-nullish-coalescing/) that warns about unnecessary assertions for non-nullish elements.

feat: add TS rule `no-non-null-asserted-nullish-coalescing`

---

svelte.mjs

To be more consistent on Svelte 5, we enforce rule [require-event-prefix](https://sveltejs.github.io/eslint-plugin-svelte/rules/require-event-prefix/) that normalizes components event-functions.

feat: Add Svelte rule `require-event-prefix`

---

configs/eslint.rules.mjs

In PR https://github.com/dfinity/eslint-config-oisy-wallet/pull/72 , I mistakenly removed rule [consistent-type-definitions](https://typescript-eslint.io/rules/consistent-type-definitions/) while rebasing...

feat(frontend): re-introduce rule consistent-type-definitions

---

vitest.mjs

I would like to propose the vitest rule [prefer-mock-promise-shorthand](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/prefer-mock-promise-shorthand.md):
```ts
// bad
vi.fn().mockReturnValue(Promise.reject(42))
vi.fn().mockImplementation(() => Promise.resolve(42))
// good
vi.fn().mockRejectedValue(42)
vi.fn().mockResolvedValue(42)
```

feat: add vitest rule `prefer-mock-promise-shorthand`

---

vitest.mjs

To be more explicit and better monitor missing tests, we add vitest rule [prefer-todo](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/prefer-todo.md) that enforces the use of `test.todo` instead of
```ts
test('foo');
test('foo', () => {})
test.skip('foo', () => {})
```

feat: add vitest rule `prefer-todo`

---

.github/actions/prepare/action.yml

We want to use Node LTS.
This might also resolve the publishing issue we had in https://github.com/dfinity/eslint-config-oisy-wallet/actions/runs/15063303915/job/42342507748

chore: use Node v22 in CI

---

configs/eslint.rules.mjs

I misjudged rule [no-unnecessary-condition](https://typescript-eslint.io/rules/no-unnecessary-condition): there is a known limitation that returns false positive for [possibly-undefined indexed access](https://typescript-eslint.io/rules/no-unnecessary-condition/#possibly-undefined-indexed-access).
So, for example, the snippet
```ts
const randomMap: Record<number, { value: string }> = {}
randomMap?.[123].value
```
will raise a lint warning. While, if we remove the coalescing
```ts
const randomMap: Record<number, { value: string }> = {}
randomMap[123].value
```
it will not raise a lint warning, but it will fail at runtime.
Since this is a very common use-case, my suggestion is to remove the rule.

fix: Remove TS rule `no-unnecessary-condition`

---

package-lock.json
package.json

We want to release a patch v0.1.12 to include fix https://github.com/dfinity/eslint-config-oisy-wallet/pull/121

chore: Bump version for release v0.1.12

---

svelte.mjs

We introduce Svelte lint rule [prefer-const](https://sveltejs.github.io/eslint-plugin-svelte/rules/prefer-const/), that warns about unnecessary mutable variables in Svelte components.
In Svelte 5, some variables are defined using runes. By default the runes excluded by this lint rule are `$props` and `$derived`.
However, we decided (see [thread](https://github.com/dfinity/gix-components/pull/631#discussion_r2091543928)) to leave mutable variables when they are defined by `$state`. So we exclude it from the rule too.

feat: Add Svelte rule `prefer-const`

---

configs/eslint.rules.mjs

We would like to avoid the usage of the non-null assertion `!` in the code, so we introduce rule [no-non-null-assertion](https://typescript-eslint.io/rules/no-non-null-assertion/).

feat: Add rule `no-non-null-assertion`

---

package-lock.json
package.json

I have trouble install ic-js and agent-js beta because the linter requires utils v2. I think we can makes it accept anything above.
Potentially we can even close to accept * because isNullish etc. were introduced in utils [v0.0.13](https://github.com/dfinity/ic-js/releases/tag/v0.15.0) but, let's try first like this.
- Accept `>=` instead of `^`

feat: accept peer dfinity utils as of v2 not only v2

---

package-lock.json
package.json

The peer dependencies on `@dfinity/utils` in this linter is pain. Everywhere we use it, either it throws error, block or throw warning while fundamentally speaking we do not care if the linter inherits or not that lib. So while it is not fully correct to require `*` since the nullish utils were introduced in v0.0.1x something, we still set `*` as peer to avoid being annoyed.

build: accept any utils

---

README.md
configs/eslint.rules.mjs
rules/use-nullish-checks.cjs
rules/use-option-type-wrapper.cjs

According to suggestion https://github.com/dfinity/eslint-config-oisy-wallet/issues/135, it make sense to disable local rule `use-option-type-wrapper` by default: it may happen that the consumer does not want to create/use the `Option` type.
The consumer can always turn it on if necessary (updated documentation).
NOTE: local rule `use-nullish-checks` was under the same circumnstances, but its metadata were not updated.

feat: Disable local rule `use-option-type-wrapper` by default

---

vitest.mjs

To be more consistent, we add vitest rule [no-importing-vitest-globals](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/no-importing-vitest-globals.md) that disallows importing [Vitest globals](https://vitest.dev/config/#globals).

feat: add vitest rule `no-importing-vitest-globals`

---

vitest.mjs

We add vitest rule [prefer-called-once](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/prefer-called-once.md) that enforces the use of `toBeCalledOnce()` or `toHaveBeenCalledOnce()`.

feat: add vitest rule `prefer-called-once`

---

svelte.mjs

To be more consistent, we enforce Svelte rule [sort-attributes](https://sveltejs.github.io/eslint-plugin-svelte/rules/sort-attributes/) that sorts all the props of a component when rendered/called.
We use it with the default settings. The default order is:
`this` property.
`bind:this` directive.
`id` attribute.
`name` attribute.
`slot` attribute.
`--style-props` (Alphabetical order within the same group.)
`style` attribute, and `style:` directives.
`class` attribute.
`class:` directives. (Alphabetical order within the same group.)
other attributes. (Alphabetical order within the same group.)
`bind:` directives (other then `bind:this`), and `on:` directives.
`use:` directives. (Alphabetical order within the same group.)
`transition:` directive.
`in:` directive.
`out:` directive.
`animate:` …

feat: Add Svelte rule `sort-attributes`

---

configs/eslint.rules.mjs

We would like to avoid unnecessary `return` statements, so we introduce rule [no-useless-return](https://eslint.org/docs/latest/rules/no-useless-return).

feat: Add rule no-useless-return
